language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"
matrix:
  allow_failures:
    - python: "nightly"
branches:
  only:
    - master
    - dev
install:
  - pip install -r requirements.txt
# command to run tests
script: sh scripts/test.sh
