language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"
matrix:
  allow_failures:
    - python: "nightly"
install:
  - pip install -r requirements.txt
  - pip install .
# command to run tests
script: pytest
